PREFIX: "&6&lGiantKoTH &8• "
NOT_PLAYER: "%prefix% &cYou are not a player."
NO_PERMISSION: "%prefix% &cYou dont have permission to execute this command."

KOTH_ENTRY_ZONE: "%prefix% &fTu entres dans la zone du KoTH &a%name%&f."
KOTH_LEAVE_ZONE: "%prefix% &fTu quittes la zone du KoTH &a%name%&f."

KOTH_GIANT:
  SPACER_MESSAGE_UP:
    - "&7&m-----------------------------------------------"
    - ""
  SPACER_MESSAGE_DOWN:
    - ""
    - "&7&m-----------------------------------------------"
  LIST_FORMAT: "&7➤ &6%koth_name% &7• &f(%world%, %x%;%z%)"
  PLAYER_NO_PERM:
    - "&7&m-----------------------------------------------"
    - ""
    - " &7▶ &e/giantkoth list &7• &fAfficher la liste des KoTH's"
    - " &7▶ &e/giantkoth show <nom> &7• &fAfficher les coordonnées d'un KoTH"
    - ""
    - "&7&m-----------------------------------------------"
  ADMIN:
    - "&7&m-----------------------------------------------"
    - ""
    - " &7▶ &e/giantkoth list &7• &fAfficher la liste des KoTH's"
    - " &7▶ &e/giantkoth show <nom> &7• &fAfficher les coordonnées d'un KoTH"
    - " &7▶ &e/giantkoth start <nom> <time> &7• &fDémarrer un KoTH"
    - " &7▶ &e/giantkoth stop <nom> &7• &fArrêter un KoTH"
    - " &7▶ &e/giantkoth tp <nom> &7• &fSe téléporter a un KoTH"
    - " &7▶ &e/giantkoth create <nom> &7• &fCréer un KoTH"
    - " &7▶ &e/giantkoth remove <nom> &7• &fSupprimer un KoTH"
    - " &7▶ &e/giantkoth setarea <nom> &7• &fCréer la zone du KoTH"
    - " &7▶ &e/giantkoth setzone <nom> &7• &fCréer la zone de capture du KoTH"
    - ""
    - "&7&m-----------------------------------------------"
  CONSOLE:
    - "&7&m-----------------------------------------------"
    - ""
    - " &7▶ &e/giantkoth list &7• &fAfficher la liste des KoTH's"
    - " &7▶ &e/giantkoth show <nom> &7• &fAfficher les coordonnées d'un KoTH"
    - " &7▶ &e/giantkoth start <nom> <time> &7• &fDémarrer un KoTH"
    - " &7▶ &e/giantkoth stop <nom> &7• &fArrêter un KoTH"
    - ""
    - "&7&m-----------------------------------------------"
  SYMBOL_NO_COORDS: "&4✘"
  SHOW_MESSAGE:
    - "&7&m-----------------------------------------------"
    - ""
    - "&6&l%koth_name%"
    - " &7• &fLocalisation: &7(&a%x%,%z%&7)"
    - ""
    - "&7&m-----------------------------------------------"
  NOT_EXIST: "%prefix% &cCe KoTH n'existe pas."
  STOP_BROADCAST: "%prefix% &fLe KoTH &a%name% &fvient subitement de se terminer..."
  NOT_REGION_SELECTED: "%prefix% &cTu dois séléctionner une région."
  SUCCESS_CREATE_ZONE: "%prefix% &fTu viens de créer la zone du KoTH &a%name%"
  SUCCESS_CREATE: "%prefix% &fTu viens de créer le KoTH &a%name%&f."
  SUCCESS_REMOVE: "%prefix% &fTu viens de supprimer le KoTH &a%name%&f."
  SUCCESS_START_BROADCAST: "%prefix% &fLe KoTH &a%name% &fvient de débuter ! Sois le premier à le capturer."
  ALREADY_START: "%prefix% &fLe KoTH &a%name% &fest déjà activé !"
  UPDATE_POINTS: "%prefix% &fTu viens de modifier les points du Koth."
  ENTRY_ZONE_CAP: "%prefix% &fTu entres dans la zone de capture du Koth &a%name%&f."
  LEAVE_ZONE_CAP: "%prefix% &fTu quittes la zone de capture du Koth &a%name%&f."
  END_MESSAGE:
    - "&7&m-----------------------------------------------"
    - ""
    - "&fLe KoTH à points &a%name% &fest terminé !"
    - "&fGagnant: &6&l%faction_name%"
    - ""
    - "&7&m-----------------------------------------------"
  END_MESSAGE_NO_WINNER:
    - "&7&m-----------------------------------------------"
    - ""
    - "&fLe KoTH &a%name% &fest terminé !"
    - "&fGagnant: &4&l✘"
    - ""
    - "&7&m-----------------------------------------------"

KOTH_GIANT_REWARDS:
  REWARDS:
    1:
      NUMBER: 1
      COMMANDS:
        - "classement add pvp %faction% 60"
    2:
      NUMBER: 2
      COMMANDS:
        - "classement add pvp %faction% 40"
    3:
      NUMBER: 3
      COMMANDS:
        - "classement add pvp %faction% 30"