PREFIX: "&6&lGiantKoTH &8• "
NOT_PLAYER: "%prefix% &cYou are not a player."
NO_PERMISSION: "%prefix% &cYou dont have permission to execute this command."

KOTH_ENTRY_ZONE: "%prefix% &fYou are now entering &a%name%&f."
KOTH_LEAVE_ZONE: "%prefix% &fYou are now leaving &a%name%&f."

KOTH_GIANT:
  SPACER_MESSAGE_UP:
    - "&7&m-----------------------------------------------"
    - ""
  SPACER_MESSAGE_DOWN:
    - ""
    - "&7&m-----------------------------------------------"
  LIST_FORMAT: "&7➤ &6%koth_name% &7• &f(%world%, %x%;%z%)"
  PLAYER_NO_PERM:
    - "&7&m-----------------------------------------------"
    - ""
    - " &7▶ &e/giantkoth list &7• &fPrint koth list"
    - " &7▶ &e/giantkoth show <nom> &7• &fPrint koth coords"
    - ""
    - "&7&m-----------------------------------------------"
  ADMIN:
    - "&7&m-----------------------------------------------"
    - ""
    - " &7▶ &e/giantkoth list &7• &fPrint koth list"
    - " &7▶ &e/giantkoth show <name> &7• &fPrint koth coords"
    - " &7▶ &e/giantkoth start <name> <time> &7• &fStart KoTH"
    - " &7▶ &e/giantkoth stop <name> &7• &fStop KoTH"
    - " &7▶ &e/giantkoth tp <name> &7• &fTeleport to KoTH"
    - " &7▶ &e/giantkoth points <name> <number> &7• &fChange capture points"
    - " &7▶ &e/giantkoth create <name> &7• &fCreate KoTH"
    - " &7▶ &e/giantkoth remove <name> &7• &fDelete KoTH"
    - " &7▶ &e/giantkoth setarea <name> &7• &fCreate KoTH Area"
    - " &7▶ &e/giantkoth setzone <name> &7• &fCreate KoTH capture zone"
    - ""
    - "&7&m-----------------------------------------------"
  CONSOLE:
    - "&7&m-----------------------------------------------"
    - ""
    - " &7▶ &e/giantkoth list &7• &fPrint koth list"
    - " &7▶ &e/giantkoth show <name> &7• &fPrint koth coords"
    - " &7▶ &e/giantkoth start <name> <time> &7• &fStart KoTH"
    - " &7▶ &e/giantkoth stop <name> &7• &fStop KoTH"
    - ""
    - "&7&m-----------------------------------------------"
  SYMBOL_NO_COORDS: "&4✘"
  SHOW_MESSAGE:
    - "&7&m-----------------------------------------------"
    - ""
    - "&6&l%koth_name%"
    - " &7• &fLocalisation: &7(&a%x%,%z%&7)"
    - ""
    - "&7&m-----------------------------------------------"
  NOT_EXIST: "%prefix% &cThis KoTH is not exist."
  STOP_BROADCAST: "%prefix% &fThis KoTH &a%name% &fis now ending."
  NOT_REGION_SELECTED: "%prefix% &cYou have to select a region."
  SUCCESS_CREATE_ZONE: "%prefix% &fYou create the KoTH area of &a%name%"
  SUCCESS_CREATE: "%prefix% &fYou create a new KoTH: &a%name%&f."
  SUCCESS_REMOVE: "%prefix% &fYou delete KoTH: &a%name%&f."
  SUCCESS_START_BROADCAST: "%prefix% &fKoTH &a%name% &fis now starting."
  ALREADY_START: "%prefix% &fKoTH &a%name% &fis already online !"
  UPDATE_POINTS: "%prefix% &fYou edit the max KoTH points."
  ENTRY_ZONE_CAP: "%prefix% &fYou are now entering on capture zone of &a%name%&f."
  LEAVE_ZONE_CAP: "%prefix% &fYou are now leaving on capture zone of &a%name%&f."
  END_MESSAGE:
    - "&7&m-----------------------------------------------"
    - ""
    - "&fKoTH &a%name% &fis now finish !"
    - "&fWinner: &6&l%faction_name%"
    - ""
    - "&7&m-----------------------------------------------"
  END_MESSAGE_NO_WINNER:
    - "&7&m-----------------------------------------------"
    - ""
    - "&fKoTH &a%name% &fis finish !"
    - "&fWinner: &4&l✘"
    - ""
    - "&7&m-----------------------------------------------"

KOTH_GIANT_REWARDS:
  REWARDS:
    1:
      NUMBER: 1
      COMMANDS:
        - "classement add pvp %faction% 60"
    2:
      NUMBER: 2
      COMMANDS:
        - "classement add pvp %faction% 40"
    3:
      NUMBER: 3
      COMMANDS:
        - "classement add pvp %faction% 30"